### ISSUE TITLE
-ltriSurface no longer exists in ext-3.2

### ISSUE THREAD

**Issue by Azrael3000** [wyldckat/FluidStructureInteraction#1]
Running the beamInCrossFlow fails at the compilation stage because from a fresh install of ext-3.2 the libtriSurface.so no longer exists. According to

https://sourceforge.net/p/openfoam-extend/ticketsfoamextendrelease/281/

this has been moved into libmeshTools.so, so the Makefile options should be updated accordingly.

see also:

https://sourceforge.net/p/openfoam-extend/swak4Foam/ci/default/tree/Libraries/rules/versionOptions

where the TRISURFACE_LIB variable is removed for certain versions.

Obviously the fix is simple, since you have version dependent branches just remove all notions of -ltriSurface

**Comment by wyldckat** [comment]
Many thanks for the details! I wasn't able to make the test+commit+push today, but it's now on my to-do list.

If want/can/prefer a faster fix, you can issue a pull request and I'll quickly merge it.

**Comment by wyldckat** [comment]
Many thanks once again! I also noticed from your pull request that there are some temporary build files that should not be indexed in git form. I'll clean it up as soon as I can.

**Comment by Azrael3000** [comment]
Yeah I thought that they should not be there, but wasn't quite sure about it. You're welcome and thanks for providing this plugin.

**Comment by wyldckat** [comment]
> thanks for providing this plugin.

Please keep in mind that I've only done some housekeeping on the code, I did not write the code itself ;)
And do expect that the solver will crash right after the end of the simulation, due to an overlap of object names within the source code.

By the way, there is a more recent iteration of this FSI toolkit, available here: http://openfoamwiki.net/index.php/Extend-bazaar/Toolkits/Fluid-structure_interaction#Install_on_foam-extend-4.0

foam-extend 4.0 hasn't been released yet, but you can find the pre-release version on the `nextRelease` branch on the foam-extend 3.2 repository. The issue with _solver will crash right after the end of the simulation_ will be sorted out once they merge the FSI toolkit into foam-extend 4.0.
